name: dinner_tonight
description: "一个帮助决定今晚吃什么的Flutter应用"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  sqflite: ^2.3.0
  sqflite_common_ffi: ^2.3.2
  path: ^1.8.3
  path_provider: ^2.1.2
  provider: ^6.1.1
  flutter_spinkit: ^5.2.0
  shared_preferences: ^2.2.2
  intl: ^0.19.0
  font_awesome_flutter: ^10.7.0
  lottie: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
